import React, { useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { Activity, ArrowUpRight, BarChart3, Bell, ChevronDown, CircleHelp, LineChart, RefreshCw, Settings2, ShieldCheck, SlidersHorizontal, TrendingDown, TrendingUp, X } from 'lucide-react'
import { getWatchlistSnapshot } from './data/marketData.js'
import { scanSetups } from './logic/scanner.js'
import './styles.css'

const watchlist = ['SPY', 'QQQ', 'IWM', 'NVDA', 'TSLA', 'AAPL', 'AMD', 'META', 'AMZN']
const formatPrice = (value) => `$${value.toFixed(2)}`

function ScoreRing({ score }) { return <div className={`score-ring score-${score >= 75 ? 'high' : score >= 60 ? 'medium' : 'low'}`}><strong>{score}</strong><span>/100</span></div> }
function TrendBadge({ trend }) { const bullish = trend === 'Bullish'; return <span className={`trend-badge ${bullish ? 'is-bullish' : 'is-bearish'}`}>{bullish ? <TrendingUp size={14} /> : <TrendingDown size={14} />}{trend}</span> }

function App() {
  const [threshold, setThreshold] = useState(65)
  const [selectedSymbol, setSelectedSymbol] = useState('SPY')
  const [watchlistOpen, setWatchlistOpen] = useState(false)
  const [lastUpdated, setLastUpdated] = useState('09:41:12 ET')
  const snapshot = useMemo(() => getWatchlistSnapshot(watchlist), [])
  const results = useMemo(() => scanSetups(snapshot), [snapshot])
  const selected = results.find((item) => item.symbol === selectedSymbol) ?? results[0]
  const qualified = results.filter((item) => item.score >= threshold)
  const bullishCount = results.filter((item) => item.status === 'Bullish').length
  const averageScore = Math.round(results.reduce((total, item) => total + item.score, 0) / results.length)
  const refreshData = () => setLastUpdated(`${new Date().toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit', second: '2-digit', hour12: false })} ET`)

  return <div className="app-shell">
    <header className="topbar"><div className="brand"><div className="brand-mark"><Activity size={19} /></div><div><strong>SetupScan</strong><span>MARKET RESEARCH CONSOLE</span></div></div><div className="market-status"><span className="status-dot" /> Market open <span className="market-time">09:41 ET</span></div><button className="icon-button" aria-label="Notifications"><Bell size={18} /></button></header>
    <main className="dashboard">
      <section className="hero-row"><div><p className="eyebrow">RULE-BASED SETUP SCANNER</p><h1>Find the signal<br /><em>before the noise.</em></h1><p className="hero-copy">A disciplined read on trend, momentum, and participation across your core watchlist.</p></div><div className="hero-meta"><div className="data-freshness"><span className="status-dot" /> Demo data · delayed snapshot</div><button className="refresh-button" onClick={refreshData}><RefreshCw size={15} /> Refresh <span>{lastUpdated}</span></button></div></section>
      <section className="summary-grid"><div className="summary-card"><div className="summary-label">Scanned today <BarChart3 size={16} /></div><strong>{results.length}</strong><span>symbols monitored</span></div><div className="summary-card highlight"><div className="summary-label">Qualified setups <ArrowUpRight size={16} /></div><strong>{qualified.length.toString().padStart(2, '0')}</strong><span>above {threshold} score threshold</span></div><div className="summary-card"><div className="summary-label">Market posture <Activity size={16} /></div><strong>{bullishCount > 4 ? 'Constructive' : 'Mixed'}</strong><span>{bullishCount} bullish signals active</span></div><div className="summary-card"><div className="summary-label">Average score <LineChart size={16} /></div><strong>{averageScore}</strong><span>across watchlist</span></div></section>
      <div className="content-grid"><section className="scanner-panel panel"><div className="panel-heading"><div><p className="eyebrow">LIVE SCAN</p><h2>Setup scanner</h2></div><button className="filter-button"><SlidersHorizontal size={15} /> Filters <ChevronDown size={14} /></button></div><div className="table-wrap"><table><thead><tr><th>Symbol</th><th>Price</th><th>Trend</th><th>VWAP</th><th>EMA 9 / 21</th><th>RSI</th><th>Rel. vol.</th><th>Score</th><th>Status</th></tr></thead><tbody>{results.map((item) => <tr key={item.symbol} className={selectedSymbol === item.symbol ? 'selected-row' : ''} onClick={() => setSelectedSymbol(item.symbol)}><td><div className="symbol-cell"><span className="ticker-dot">{item.symbol.slice(0, 1)}</span><strong>{item.symbol}</strong></div></td><td className="price-cell">{formatPrice(item.price)}<small className={item.change >= 0 ? 'positive' : 'negative'}>{item.change >= 0 ? '+' : ''}{item.change.toFixed(2)}%</small></td><td><TrendBadge trend={item.trend} /></td><td>{formatPrice(item.vwap)}</td><td><span className={item.ema9 > item.ema21 ? 'positive' : 'negative'}>{formatPrice(item.ema9)}</span><small> / {formatPrice(item.ema21)}</small></td><td><span className={item.rsi > 50 ? 'positive' : 'negative'}>{item.rsi}</span></td><td>{item.relativeVolume.toFixed(2)}x</td><td><ScoreRing score={item.score} /></td><td><span className={`status-pill ${item.status.toLowerCase().replace(' ', '-')}`}>{item.status}</span></td></tr>)}</tbody></table></div><div className="mobile-list">{results.map((item) => <button className={`mobile-row ${selectedSymbol === item.symbol ? 'selected-row' : ''}`} key={item.symbol} onClick={() => setSelectedSymbol(item.symbol)}><div className="symbol-cell"><span className="ticker-dot">{item.symbol.slice(0, 1)}</span><strong>{item.symbol}</strong><TrendBadge trend={item.trend} /></div><div className="mobile-score"><ScoreRing score={item.score} /><span className={`status-pill ${item.status.toLowerCase().replace(' ', '-')}`}>{item.status}</span></div></button>)}</div></section>
        <aside className="side-column"><section className="qualified-panel panel"><div className="panel-heading compact"><div><p className="eyebrow">THRESHOLD ≥ {threshold}</p><h2>Qualified setups</h2></div><span className="count-badge">{qualified.length}</span></div>{qualified.length ? qualified.map((item) => <button className="qualified-row" key={item.symbol} onClick={() => setSelectedSymbol(item.symbol)}><div><strong>{item.symbol}</strong><span>{item.setupType}</span></div><div className="qualified-score">{item.score}<small>/100</small><ArrowUpRight size={14} /></div></button>) : <div className="empty-state">No setups meet this threshold yet.</div>}<div className="threshold-control"><div><span>Minimum score</span><strong>{threshold}</strong></div><input type="range" min="40" max="90" value={threshold} onChange={(event) => setThreshold(Number(event.target.value))} /></div></section><section className="watchlist-panel panel"><div className="panel-heading compact"><div><p className="eyebrow">MARKETS</p><h2>Watchlist</h2></div><button className="icon-button small" onClick={() => setWatchlistOpen(!watchlistOpen)} aria-label="Manage watchlist"><Settings2 size={16} /></button></div><div className="watchlist-chips">{watchlist.map((symbol) => <button className={selectedSymbol === symbol ? 'active' : ''} key={symbol} onClick={() => setSelectedSymbol(symbol)}>{symbol}</button>)}</div><div className="secure-note"><ShieldCheck size={15} /><span>Provider-ready architecture<br /><small>No API keys stored in the client</small></span></div></section></aside></div>
      <section className="detail-grid"><section className="detail-panel panel"><div className="detail-header"><div><p className="eyebrow">SETUP BREAKDOWN</p><h2>Why {selected.symbol} scored {selected.score}</h2></div><TrendBadge trend={selected.trend} /></div><div className="detail-metrics"><div><span>Last price</span><strong>{formatPrice(selected.price)}</strong><small className={selected.change >= 0 ? 'positive' : 'negative'}>{selected.change >= 0 ? '+' : ''}{selected.change.toFixed(2)}% today</small></div><div><span>Setup type</span><strong>{selected.setupType}</strong><small>{selected.status === 'No Setup' ? 'Waiting for confirmation' : 'Conditions aligned'}</small></div></div><div className="reason-list">{selected.reasons.map((reason) => <div className="reason-item" key={reason.label}><span className={reason.points > 0 ? 'reason-positive' : 'reason-neutral'}>{reason.points > 0 ? '+' : ''}{reason.points}</span><div><strong>{reason.label}</strong><p>{reason.detail}</p></div></div>)}</div></section><section className="backtest-panel panel"><div className="panel-heading compact"><div><p className="eyebrow">NEXT MODULE</p><h2>Backtest lab</h2></div><span className="coming-soon">SCAFFOLD</span></div><div className="chart-placeholder"><div className="chart-grid"><span /><span /><span /><span /></div><div className="chart-line" /></div><div className="backtest-copy"><strong>Historical testing is ready to connect.</strong><p>The scanner exposes a reusable strategy contract for candles, signals, entries, exits, and performance metrics.</p><button className="outline-button" onClick={() => alert('Backtest runner scaffold is ready for historical data.')}>View framework <ArrowUpRight size={14} /></button></div></section></section>
      <footer><span><CircleHelp size={14} /> Scores are rule-based research signals, not probabilities or financial advice.</span><span>Data provider: Local demo adapter</span></footer>
    </main>
    {watchlistOpen && <div className="toast"><span>Watchlist is ready for provider settings.</span><button onClick={() => setWatchlistOpen(false)} aria-label="Close"><X size={16} /></button></div>}
  </div>
}

createRoot(document.getElementById('root')).render(<App />)